name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.14.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.2
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Lint
        run: |
          make lint

      - name: Test
        run: |
          make test

      - name: Distribute
        run: |
          make distribute

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: xcode-select-alfred.alfredworkflow
          path: ./dist/xcode-select-alfred.alfredworkflow

      - name: Create release note
        id: create_release_note
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release assets
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_note.outputs.upload_url }}
          asset_path: ./dist/xcode-select-alfred.alfredworkflow
          asset_name: xcode-select-alfred.alfredworkflow
          asset_content_type: application/zip
